default_language_version:
  python: python3.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2500']
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.267'
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: clean
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false